import requests

url = "http://localhost:5000/combine-match"

payload = {
    "resume": "Leonardo Nigro Computer Engineering Jobs@leonardonigro.com www.leonardonigro.com https://github.com/Leosly7663 TECHNICAL SKILLS Programming Languages: JavaScript, Python, C, Java, MySQL Frameworks and Services: React, AWS, Flask, GitHub, Azure DevOps, MS Power Platform Operating Systems: Windows XP/Vista/10/11, Linux Mint/Ubuntu/Red Hat, MacOS PROFESSIONAL EXPERIENCE Coop Student Software Solutions | Government of Canada June 2024 - May 2025 • Conceptualized and designed the IT skills and personal development center. • Met directly with clients to deliver a superior solution that met all requirements and use cases. • Deployed a fully functional internal tool to be used inter-departmentally throughout the government with a userbase of 1000+ civilian and IT developers. Student Developer | Life of A Server INC. April 2023 – Dec 2023 • Proficiently used Typescript with React to ensure scalable industry-standard code. • Maintained AWS EC2 and RDS instances for E-Commerce center leveraging a monolithic architecture. • Documented sprints, story points, logs, issues, bugs, source control, and workflows through GitHub. PROJECTS WEATHER DATA ANALYSIS | Personal Project February 2024 • Developed a Python web-scraping script to pull live data from weather.gc.ca and store in a document-style database, collecting data from 100+ cities. • Utilized GitHub Actions to automate scripting calls every hour allowing for a constant stream of data. • Plotted best fits, percentile error, standard deviation and regression through Matplotlib. PYTHON WEATHER HUD | Personal Project January 2024 • Integrated beautifulsoup4 and pillow to facilitate the download of scraped images and temporarily cache them for immediate retrieval without API calls. • Built a UI through tk desktop with custom settings and city selection. POWERPOINT GPT | Personal Project February 2022 • Developed a fully functional Python wrapper to interact with GPT-4.0 API access keys, seamlessly incorporating Python's capabilities into PowerPoint generation. • Integrated python-pptx to develop automated presentation generation. Facilitated dynamic slide creation using content generated by GPT-4.0, enabling rapid production of professional-quality presentations. Astro Brick | Personal Project May 2021 • Created a retro style mini game in JavaScript for web with player lives, a pause menu, and immersive controls. • Due to a lack of game engine, mouse tracking, player movement, and collisions were all hard-coded in JS. EDUCATION The University of Guelph | Bachelor of Engineering Computer Engineering Co-op April 2027 Relevant Courses Software: Data Structures, Object Oriented Programming, Discrete Structures in Computing Relevant Courses Hardware: Computer Architecture, Digital Design, Computer Organization, Electric Circuits http://www.leonardonigro.com/ https://github.com/Leosly7663",
    "jobSentences": [
    "Experience working with cloud services like AWS.",
    "Ability to build user interfaces with React.",
    "Knowledge of data analysis and visualization."
  ]
}
response = requests.post(url, json=payload)
print("\n===== STATUS CODE =====")
print(response.status_code)

print("\n===== RAW TEXT =====")
print(repr(response.text))   # Show even empty responses

try:
    data = response.json()
    print("\n===== PARSED JSON =====")
    print(data)
except Exception as e:
    print("\n===== JSON PARSE ERROR =====")
    print(e)
